#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_7
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_6
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_38 // 主麦 + 副麦
// #define AUDIO_I2S_MIC_GPIO_DIN2 GPIO_NUM_5  // 副麦
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_9
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_10
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_11

#define BUILTIN_LED_GPIO        GPIO_NUM_4
#define BOOT_BUTTON_GPIO        GPIO_NUM_0

#define DISPLAY_SDA_PIN GPIO_NUM_41
#define DISPLAY_SCL_PIN GPIO_NUM_42
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true


// A MCP Test: Control a lamp
#define LAMP_GPIO GPIO_NUM_18

#endif // _BOARD_CONFIG_H_
